"""empty message

Revision ID: 638f42e861c9
Revises: 63c22efd4957
Create Date: 2025-08-30 11:08:45.838617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638f42e861c9'
down_revision = '63c22efd4957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=False),
    sa.Column('post_id', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comentarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='comentarios_pkey')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
